sudo: required
dist: trusty
addons:
  apt:
    packages:
    - bsdtar
    - gettext
    - chromium-chromedriver
  chrome: stable
language: python
python:
  - "3.5"
install:
# Install chromedriver
  - ln -s /usr/lib/chromium-browser/chromedriver ~/bin/chromedriver
# Install GLaDOS
  - "pip install -r requirements.txt"
  - python setup.py install
before_script:
# Start server
  - python -m glados.manage compilemessages
  - python -m glados.manage makemigrations
  - python -m glados.manage migrate
  - python -m glados.manage runserver 8000  2>&1 | grep -v 200 | grep -v 304 &
  - sleep 60 # give Web server some time to bind to sockets, etc
script:
  - "./run_tests_no_install.sh"
