sudo: required
dist: xenial
env:
  matrix:
  - MOZ_HEADLESS=1
  global:
    secure: eW0Rb8OWmzUryDuU03KwuoZX76kfOXAx1fT0Q3w8tjVvfnyaxbLZ2tmGueHE0IpreAHtFeuxNHX10LrLg2Eu+DcHDvEfB2D1tZe/njKAfPQnm+bfYTCJLlW3UmTVB9h4xvmM8HUdL5Ku3cY0ZDNRb/E1D8JJJLyEbjyZbBlI8pbas5c1M5lgY/a2dWk7/QSJOfAb9m30GeB0uUuzOXhMT0wOh5Hc+xu8BpPXgNjSOSaWI52SUjv52TIX/C+b9dpINuNRFg9LmnH5x+oyew4HszgFvyWwTvRdHoUxouFwz5DEZfMy49tPSeYiZTxMe4jCqim4vIWU+nbAO8L8YQEewhefGuZsKULY5KzjXqSF1GTWIrLplQw8yyrJisPpmTPfm/BA4dj4ag/5DiZvlrBSp8YSo+wiyaD4CtKPTw2LGHEsjVLDQ52XN/u/BzusUUw6ZVgNGvREolFMdLdIrZv86xM+tTUlTVHmRWGDt9lgEhf7ZeK7JeelfY5Gm1qUVXNLln3hmivp+Jte9YED7Vx8lwaobdhFLTcbhwmvy4cCB3w8EiqiusxlwnFZ7UqftLaWcYJSum3M9awgcI5wzXgtIHKjk8qxEHzuwkprAAUFLIElnlhn2kkbiCU+tEPouOcSk6RyqoBjQBuIMsWSLJeRcU+wYd+3ciC5csyZmRlbUco=
addons:
  firefox: latest
  apt:
    packages:
    - bsdtar
    - gettext
  chrome: stable
language: python
python:
- '3.5'
before_install:
- wget https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz
- mkdir geckodriver
- tar -xzf geckodriver-v0.24.0-linux64.tar.gz -C geckodriver
- export PATH=$PATH:$PWD/geckodriver
install:
- pip install -r requirements.txt
- python setup.py install
before_script:
- mkdir -p $HOME/.chembl-glados
- cp configurations/default_travis_config.yml $HOME/.chembl-glados/config.yml
- "./manage_glados_no_install.sh makemigrations"
- "./manage_glados_no_install.sh migrate"
- "./manage_glados_no_install.sh compilemessages"
- "./manage_glados_no_install.sh runserver 8000  2>&1 | grep -v 200 | grep -v 304
  &"
- sleep 60
script:
- "./run_tests_no_install.sh"
