language: python
python:
  - "3.5"
install:
  - "pip install -r requirements.txt"
  - python setup.py install
before_script:
  - python -m glados.manage migrate
  - python -m glados.manage runserver 8000 &
  - sleep 10 # give Web server some time to bind to sockets, etc
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 10 # give xvfb some time to start
script:
  - "./run_tests_no_install.sh"
addons:
  firefox: "44.0"
  apt:
    packages: memcached