sudo: required
dist: trusty
addons:
  apt:
    packages:
    - bsdtar
    - gettext
    - chromium-chromedriver
  chrome: stable
language: python
python:
- '3.5'
install:
- ln -s /usr/lib/chromium-browser/chromedriver ~/bin/chromedriver
- pip install -r requirements.txt
- python setup.py install
before_script:
- mkdir -p $HOME/.chembl-glados
- cp configurations/default_travis_config.yml $HOME/.chembl-glados/config.yml
- "./manage_glados_no_install.sh makemigrations"
- "./manage_glados_no_install.sh migrate"
- "./manage_glados_no_install.sh compilemessages"
- "./manage_glados_no_install.sh runserver 8000  2>&1 | grep -v 200 | grep -v 304 &"
- sleep 60
script:
- "./run_tests_no_install.sh"
env:
  global:
  - secure: orjMVoVgRtcuvBWYAVKa/pIwURozV10hDUC6YI8bTBAhhweYZyJyJ1XZeZvpWjhvMsepXcJ9/v3jmEKU/i90vX3+SVvajkZ4mumzdWInTYuqxzZUaYnH8Ivv/3axnnU0MEJPCSn98YLmjxcY2J+JJSvO8EceOTj+ivfQuyGSs9KG7k0ATCqG8rHd+EHMHaPUnQPjt1AWeFGcPRLw5/OCeGf7JI2bi/dtfp2w1fCXX8W+3+sOabgqpYCiYfehWiplnn1wVQ1XYb1loz2tLtA7NgJ/kzOMmRn8yHvueVP4qs2l9WmQPTi5Zrm3yxHWFCemPZANVZdpz6TWAorUDYY5ZmRYJjEHsCWJgwoWx8WU3dKE+2jCZlbLmYoxnZgMtUEdc0dupDmR8j/MAG3J6CVRsfAg3zAl2cBpPWbUmGosf13PBHEjeMOlFMu26phv1K3PyIfnRifJlxIi+/In1emweAN3vTFm6ewvP+W+bGzoUw4OQtyaUIzpD4GZgHpp+fiJ7VaZzqIRUhULR3e1GKk1Z3ZPzTaXJbfA8hGyHAVvGmK0MuMRiAjvz99pUTHiV9JDH1HlX+EJvw6KKLbMy5ix9enOIECXZr3XbSKIRvmSVTNJ2t7IPQL5GdvmNjBlD7HmKAlTxzRUxrB4Ms772qN6fMwU8PVq8dtc8fq50RCD3p0=
  - secure: XPsm/2yz72Mmdy8OtrU873VdmjYVZ6NIkoBvXjnuO3plSavMsuftXOYzguy3TGUdx3MbbgRsrYQwkJFLugd2oHBao0JN+v2ZRRSpPJTYAanKvLrKcdFdt1nERfubAPDl26bIjrQvTxw2R0GGN7megUChmtqWocLGGEdTD7xn6RDJvyZCxgXmukovWsA6awPU7DZlD677rOlV7bonmxq5oC8B4sigz2dQEsDBlYdQb86VEOdut0L4yC6rNkQI2HCUm7y83SBsbCdPteE13BLxioz3fGIL7qKPPEX4EP4cEITd9OSxP3H+CPB3h2ReUiCPdawVpUaKovosS5KiCnbR5jSvT6flIivOdx/OGuOMv5Sh+YdpzSOLIUZXUx0/Jy92UpqUJGRMfJ//QDBVgaJBi/Qj9Je4+0ew88nxdCwVh37VFvjPLF/WATxuw6EpYhF1v7Q0Hwqya0rvBja83LdB+fYFqLjkQBI+9lzP+bZSgKJ28cFapmJp521/zDT+S78R9+5UYlz1NSov3/DqtwstmyEQsBxoJuOe0chopmo4e88jjbZfa2JZ7lVGMKwWjFUab2v490A4ICP+x0XfJ+CfFp+wGBZAT0a1YhymNjXnBeI/TzhKh9WJ9gMGScbk688CiDgXIS6JToGQe71uvIVmuNk4dmw4tpVhtZDAx7dhmrk=
