sudo: required
dist: xenial
env:
  matrix:
  - MOZ_HEADLESS=1
  global:
    secure: HBCEnGu9jDdqTKknXL/2SDKMx9cgDdjDBbwKFRgCOFmfWOBVlwrDE+u7o+mnRZ4B/kyZsQl/RYevcM2TjpEXYx1zvzMXokYXJxDnpsJA6a5SYyJlt0t7CtWNOSEzWUdFuamrLTjzjdMnqSmN1Pdu75um8OFDw4FLnzXOWp9lB9rJpjuwZFvOS0RXKg4m68kDdOsex3w+INu16eop5/+LLpkNyBN6PL6TP2ziRVbc/jqeNBjJcIrsE/Mi6xTQSbbC5+Cvc8bMlR9XfDrB2VlVAsoKj0Ixzx9p8Xt+5wbwLeMhlFwc2jk77a7COScaOKdzdZ9NiQvTBmC/fni5hqhcIImPl2shzEKvBnQTaO4yLBq6MGyyrUMLfvz9Ajp8J4BvhhaCBloaDijGc/1rMHxq3vwlD0L4xa1yxsjA+kS67AB2dJoYYkZBLlUH881Woh8ZLMQrljvTKQ6yuw7tteGqKi2BXw6ehbIS7zC/pzyp6rH+glibmQZBNiSMA9efsm0BL4lovHmja8jt6e8VG7RYoNXyPIbJKAocHFwvMpSpVmMbDmNazoQnGi8gJZ9g3w8JIpmV7nlTKGaEobfF+iMy+BPmUX0quqZ+wMSf6HQIBjTTz64vxX6NA2w/yH1MKe/i0x8QbzMVogyic12I/Z2lKOfETIgeVrG4jwyt5meKWvA=
addons:
  firefox: latest
  apt:
    packages:
    - bsdtar
    - gettext
  chrome: stable
language: python
python:
- '3.5'
before_install:
- wget https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz
- mkdir geckodriver
- tar -xzf geckodriver-v0.24.0-linux64.tar.gz -C geckodriver
- export PATH=$PATH:$PWD/geckodriver
install:
- pip install -r requirements.txt
- python setup.py install
before_script:
- mkdir -p $HOME/.chembl-glados
- cp configurations/default_travis_config.yml $HOME/.chembl-glados/config.yml
- "./manage_glados_no_install.sh makemigrations"
- "./manage_glados_no_install.sh migrate"
- "./manage_glados_no_install.sh compilemessages"
- "./manage_glados_no_install.sh runserver 8000  2>&1 | grep -v 200 | grep -v 304
  &"
- sleep 60
script:
- "./run_tests_no_install.sh"
