sudo: required
dist: xenial
env:
  - MOZ_HEADLESS=1
addons:
  firefox: latest
  apt:
    packages:
    - bsdtar
    - gettext
  chrome: stable
language: python
python:
- '3.5'
install:
- pip install -r requirements.txt
- python setup.py install
before_script:
- mkdir -p $HOME/.chembl-glados
- cp configurations/default_travis_config.yml $HOME/.chembl-glados/config.yml
- "./manage_glados_no_install.sh makemigrations"
- "./manage_glados_no_install.sh migrate"
- "./manage_glados_no_install.sh compilemessages"
- "./manage_glados_no_install.sh runserver 8000  2>&1 | grep -v 200 | grep -v 304 &"
- sleep 60
script:
- "./run_tests_no_install.sh"