language: python
python:
  - "3.5"
install:
  - "pip install -r requirements.txt"
  - python setup.py install
before_script:
  - python -m glados.manage migrate
  - python -m glados.manage runserver 8000  2>&1 | grep -v 200 | grep -v 304 &
  - django-admin compilemessages
  - sleep 60 # give Web server some time to bind to sockets, etc
script:
  - "./run_tests_no_install.sh"
addons:
  apt:
    packages: memcached
