name: glados
channels:
- salilab
- defaults
dependencies:
- openssl=1.0.2l=0
- pip=9.0.1=py35_1
- python=3.5.3=1
- readline=6.2=2
- setuptools=27.2.0=py35_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py35_0
- xz=5.2.2=1
- zlib=1.2.8=3
- gettext=0.19.5.1=0
- pip:
  - argh==0.26.2
  - arpeggio==1.6.1
  - certifi==2017.7.27.1
  - chardet==3.0.4
  - coffeescript==1.1.2
  - django==1.10.4
  - django-appconf==1.0.2
  - django-compressor==2.1.1
  - idna==2.6
  - pathtools==0.1.2
  - pyexecjs==1.4.0
  - pyscss==1.3.5
  - python3-memcached==1.51
  - pyyaml==3.12
  - rcssmin==1.0.6
  - requests==2.18.4
  - rjsmin==1.0.12
  - selenium==2.52.0
  - six==1.10.0
  - twitter==1.17.1
  - urllib3==1.22
  - watchdog==0.8.3
  - whitenoise==3.3.0

