run_env: DEV #DEV, TRAVIS, TEST or PROD
spawn_jobs: True # When False, it doesn't use the django rq system, it just executes the function right away.
# ^ If not present, it is assumed to be True
elasticsearch:
  monitoring:
    host: 'https://wwwdev.ebi.ac.uk/chembl/elk/monitoring'
    username: chembl-mon
    password: <MONITORING_PASSWORD>
  data:
    host: 'https://wwwdev.ebi.ac.uk/chembl/elk/es'
    username: chembl-indexer
    password: <MONITORING_PASSWORD>
  public_host: 'https://wwwdev.ebi.ac.uk/chembl/elk/es'
chembl_api:
  ws_url: 'https://www.ebi.ac.uk/chembl/api/data'
  beaker_url: 'https://www.ebi.ac.uk/chembl/api/utils'
current_release:
  full_name: 'CHEMBL27'
  full_doi: 'http://doi.org/10.6019/CHEMBL.database.27'
  downloads_date: '2020-02-21'
  # The basename of the files in the ftp
  downloads_release_name: 'chembl_27'
  elasticsearch_chembl_index_prefix: 'chembl_27_'
server_secret_key: 'server_secret_key'
enable_twitter: True
twitter_secrets:
  twitter_access_token: 'twitter_access_token'
  twitter_access_token_secret: 'twitter_access_token_secret'
  twitter_access_consumer_key: 'twitter_access_consumer_key'
  twitter_access_consumer_secret: 'twitter_access_consumer_secret'
enable_blogger: True
blogger_secrets:
  blogger_key: 'blogger_key'
admin_user:
  username: 'admin'
  email: 'email'
  password: 'password'
enable_mongo_db_cache: True
mongo_db_cache_config:
  BACKEND: 'glados.cache_backend.MongoDBCache.MongoDBCache'
  LOCATION: 'LOCATION'
  OPTIONS:
    HOST:
      - "host1:12345"
      - "host2:12345"
      - "host3:12345"
    RSNAME: 'RSNAME'
    MAX_ENTRIES: 100000000000
    DATABASE: 'DATABASE'
    AUTH_DATABASE: 'AUTH_DATABASE'
    USER: 'USER'
    PASSWORD: 'PASSWORD'
    SOCKET_TIMEOUT_MS: 4000
    CONNECT_TIMEOUT_MS: 2000
    SERVER_SELECTION_TIMEOUT_MS: 2000
    MAX_TIME_MS: 1000
    COMPRESSION_LEVEL: 6
    COMPRESSION: True
enable_mysql_database: True
mysql_config:
  schema_name: 'schema_name'
  host: 'host'
  port: 'port'
  user: 'user'
  password: 'password'
custom_rq_queues_config:
  default:
    HOST: 'HOST'
    PASSWORD: 'PASSWORD'
    PORT: 1234
    DB: 0
    DEFAULT_TIMEOUT: 86400
unichemapi: 'le unichem api'
unichem_similarity_endpoint: 'le similarity endpoint'
target_prediction_lookup_file: 'api/chembl/target_prediction/prediction_lookup.csv'