run_env: TRAVIS
spawn_jobs: False # When False, it doesn't use the django rq system, it just executes the function right away.
# ^ If not present, it is assumed to be True
elasticsearch:
  host: 'https://www.ebi.ac.uk/chembl/glados-es/__secret/'
  public_host: 'https://www.ebi.ac.uk/chembl/glados-es'
chembl_api:
  ws_url: 'https://www.ebi.ac.uk/chembl/api/data'
  beaker_url: 'https://www.ebi.ac.uk/chembl/api/utils'
old_interface_url: 'https://www.ebi.ac.uk/chembl/old'
current_release:
  full_name: 'CHEMBL26'
  full_doi: 'http://doi.org/10.6019/CHEMBL.database.26'
  downloads_date: '2020-02-21'
  # The basename of the files in the ftp
  downloads_release_name: 'chembl_26'
  elasticsearch_chembl_index_prefix: 'chembl_26_'
filter_query_max_clauses: 30000
chemvue_root_api: 'http://localhost:8000'
unichem_similarity_endpoint: 'http://fakeserver/similarity'
delayed_jobs:
  base_url: 'https://www.ebi.ac.uk/chembl/interface_api/delayed_jobs'