run_env: TRAVIS
elasticsearch:
  host: 'https://www.ebi.ac.uk/chembl/glados-es'
  public_host: 'https://www.ebi.ac.uk/chembl/glados-es'
chembl_api:
  ws_url: 'https://www.ebi.ac.uk/chembl/api/data'
  beaker_url: 'https://www.ebi.ac.uk/chembl/api/utils'
old_interface_url: 'https://www.ebi.ac.uk/chembl/old'
current_chembl_release: 'CHEMBL25'
filter_query_max_clauses: 30000

chemvue_root_api: 'http://localhost:8000'
unichem_similarity_endpoint: 'http://fakeserver/similarity'