run_env: DEV #DEV, TRAVIS, TEST or PROD
elasticsearch:
  host: 'https://www.ebi.ac.uk/chembl/glados-es'
  public_host: 'https://www.ebi.ac.uk/chembl/glados-es'
chembl_api:
  ws_url: 'https://wwwdev.ebi.ac.uk/chembl/api/data'
  beaker_url: 'https://wwwdev.ebi.ac.uk/chembl/api/utils'
old_interface_url: 'https://www.ebi.ac.uk/chembl/old'
current_release:
  full_name: 'CHEMBL25'
filter_query_max_clauses: 30000
