run_env: DEV #DEV, TRAVIS, TEST or PROD
spawn_jobs: False # When False, it doesn't use the django rq system, it just executes the function right away.
# ^ If not present, it is assumed to be True
elasticsearch:
  public_host: 'https://wwwdev.ebi.ac.uk/chembl/elk/es'
chembl_api:
  ws_url: 'http://wwwdev.ebi.ac.uk/chembl/api/data'
  beaker_url: 'http://wwwdev.ebi.ac.uk/chembl/api/utils'
current_release:
  full_name: 'CHEMBL27'
  full_doi: 'http://doi.org/10.6019/CHEMBL.database.27'
  downloads_date: '2020-02-21'
  # The basename of the files in the ftp
  downloads_release_name: 'chembl_27'
  elasticsearch_chembl_index_prefix: 'chembl_27_'
