chembl_molecule:
  download:
    default: ['molecule_chembl_id', 'pref_name', 'molecule_synonyms', 'molecule_type', 'max_phase',
    'molecule_properties.full_mwt', '_metadata.related_targets.count', '_metadata.related_activities.count',
    'molecule_properties.alogp', 'molecule_properties.psa', 'molecule_properties.hba', 'molecule_properties.hbd',
    'molecule_properties.num_ro5_violations', 'molecule_properties.rtb', 'molecule_properties.ro3_pass',
    'molecule_properties.qed_weighted', 'molecule_properties.acd_most_apka', 'molecule_properties.acd_most_bpka',
    'molecule_properties.acd_logp', 'molecule_properties.acd_logd', 'molecule_properties.aromatic_rings',
    'structure_type', 'inorganic_flag', 'molecule_properties.heavy_atoms', 'molecule_properties.hba_lipinski',
    'molecule_properties.hbd_lipinski', 'molecule_properties.num_lipinski_ro5_violations',
    'molecule_properties.mw_monoisotopic', 'molecule_properties.molecular_species',
    'molecule_properties.full_molformula', 'molecule_structures.canonical_smiles']
  download_drugs:
    default: ['molecule_chembl_id', 'molecule_synonyms', 'research_codes', 'drug_phase',
    '_metadata.drug.drug_data.applicants', 'usan_stem', 'usan_year', 'usan_stem_definition',
    '_metadata.drug.drug_data.usan_stem_substem', 'first_approval', 'drug_atc_classifications', 'drug_atc_descriptions',
    'indication_class', '_metadata.drug.drug_data.sc_patent', '_metadata.drug.drug_data.drug_type',
    '_metadata.drug.drug_data.rule_of_five', '_metadata.drug.drug_data.first_in_class',
    '_metadata.compound_generated.chirality_label', '_metadata.drug.drug_data.prodrug',
    '_metadata.drug.drug_data.oral', '_metadata.drug.drug_data.parenteral', '_metadata.drug.drug_data.topical',
    '_metadata.drug.drug_data.black_box', '_metadata.compound_generated.availability_type_label',
    '_metadata.drug.drug_data.withdrawn_year', '_metadata.drug.drug_data.withdrawn_reason',
    '_metadata.drug.drug_data.withdrawn_country', '_metadata.drug.drug_data.withdrawn_class',
    'molecule_structures.canonical_smiles']
chembl_assay:
  download:
    default: ['assay_chembl_id', 'assay_type', 'description', 'assay_organism', '_metadata.related_compounds.count',
    '_metadata.related_activities.count', 'bao_format', 'bao_label', 'assay_strain', '_metadata.source.src_description',
    'assay_tax_id', 'assay_type', 'tissue_chembl_id', 'assay_tissue', 'assay_cell_type', 'assay_subcellular_fraction',
    'document_chembl_id', '_metadata.document_data.pubmed_id', '_metadata.document_data.doi',
    '_metadata.document_data.year', '_metadata.document_data.journal', '_metadata.document_data.volume',
    '_metadata.document_data.first_page','_metadata.document_data.last_page']
chembl_target:
  download:
    default: ['target_chembl_id', 'pref_name', 'uniprot_accessions', 'target_type', 'organism',
    '_metadata.related_compounds.count', '_metadata.related_activities.count', 'tax_id', 'species_group_flag']
chembl_document:
  download:
    default: ['document_chembl_id', 'journal_full_title', 'src_id', '_metadata.source', 'title', 'pubmed_id', 'doi',
    'patent_id', 'authors', 'year', 'volume', 'issue', 'first_page', 'doc_type', 'abstract',
    '_metadata.related_compounds.count', '_metadata.related_targets.count', '_metadata.related_activities.count']
chembl_cell_line:
  download:
    default: ['cell_chembl_id', 'cell_name', 'cell_description', 'cell_source_organism', 'cell_source_tissue',
    'cell_source_tax_id', 'clo_id', 'efo_id', 'cellosaurus_id', 'cl_lincs_id', '_metadata.related_compounds.count',
    '_metadata.related_activities.count']
chembl_tissue:
  download:
    default: ['tissue_chembl_id', 'pref_name', 'uberon_id', 'efo_id', 'bto_id', 'caloha_id',
    '_metadata.related_compounds.count', '_metadata.related_activities.count']
chembl_drug_indication_by_parent:
  download:
    default: ['parent_molecule.molecule_chembl_id', 'parent_molecule.pref_name', 'parent_molecule.molecule_type',
    'drug_indication.max_phase_for_ind', 'parent_molecule.first_approval', 'drug_indication.mesh_id',
    'drug_indication.mesh_heading', 'efo_ids', 'efo_terms', 'drug_indication.indication_refs',
    'parent_molecule._metadata.drug.drug_data.synonyms', 'parent_molecule._metadata.drug.drug_data.usan_stem',
    'parent_molecule._metadata.drug.drug_data.usan_year']
