chembl_molecule:
  'molecule_properties.full_mwt':
    label: 'Molecular Weight'
  '_metadata.related_targets.count':
    label: 'Targets'
  '_metadata.related_activities.count':
    label: 'Bioactivities'
  'molecule_properties.alogp':
    label: 'AlogP'
  'molecule_properties.psa':
    label: 'PSA'
  'molecule_properties.hba':
    label: 'HBA'
  'molecule_properties.hbd':
    label: 'HBD'
  'molecule_properties.num_ro5_violations':
    label: '#RO5 Violations'
  'molecule_properties.rtb':
    label: '#Rotatable Bonds'
  'molecule_properties.ro3_pass':
    label: 'Passes Ro3'
  'molecule_properties.qed_weighted':
    label: 'QED Weighted'
  'molecule_properties.acd_most_apka':
    label: 'ACD ApKa'
  'molecule_properties.acd_most_bpka':
    label: 'ACD BpKa'
  'molecule_properties.acd_logp':
    label: 'ACD LogP'
  'molecule_properties.acd_logd':
    label: 'ACD LogD'
  'molecule_properties.aromatic_rings':
    label: 'Aromatic Rings'
  'structure_type':
    label: 'Structure Type'
  'molecule_properties.hba_lipinski':
    label: 'HBA Lipinski'
  'molecule_properties.hbd_lipinski':
    label: 'HBD Lipinski'
  'molecule_properties.num_lipinski_ro5_violations':
    label: '#RO5 Violations (Lipinski)'
  'molecule_properties.mw_monoisotopic':
    label: 'Molecular Weight (Monoisotopic)'
  'molecule_properties.full_molformula':
    label: 'Molecular Formula'
  'molecule_structures.canonical_smiles':
    label: 'Smiles'
  'drug_parent_molecule_chembl_id':
    based_on: 'molecule_chembl_id'
    label: 'Parent Molecule ChEMBL ID'
  'research_codes':
    based_on: 'molecule_synonyms'
    label: 'Research Codes'
  'drug_phase':
    based_on: 'max_phase'
    label: 'Phase'
  'drug_atc_classifications':
    based_on: '_metadata.drug.drug_data.atc_classification'
    label: 'ATC Classifications'
  'drug_atc_descriptions':
    based_on: '_metadata.drug.drug_data.atc_classification'
    label: 'ATC Code Descriptions'
  '_metadata.drug.drug_data.sc_patent':
    label: 'Patent'
  '_metadata.drug.drug_data.rule_of_five':
    label: 'Passes Rule of Five'
  '_metadata.compound_generated.chirality_label':
    label: 'Chirality'
  '_metadata.compound_generated.availability_type_label':
    label: 'Availability Type'
chembl_assay:
  '_metadata.related_compounds.count':
    label: 'Compounds'
  '_metadata.related_activities.count':
    label: 'Activities'
  'bao_format':
    label: 'BAO Format ID'
  'bao_label':
    label: 'BAO Format'
  '_metadata.source.src_description':
    label: 'Source'
  'assay_tax_id':
    label: 'Tax ID'
  'assay_type':
    label: 'Assay Type'
  'assay_tissue':
    label: 'Tissue Name'
  '_metadata.document_data.pubmed_id':
    label: 'PubMed ID'
  '_metadata.document_data.doi':
    label: 'DOI'
  '_metadata.document_data.journal':
    label: 'Journal'
  '_metadata.document_data.year':
    label: 'Year'
  '_metadata.document_data.volume':
    label: 'Volume'
  '_metadata.document_data.first_page':
    label: 'First Page'
  '_metadata.document_data.last_page':
    label: 'Last Page'
chembl_target:
  'pref_name':
    label: 'Name'
  'uniprot_accessions':
    based_on: 'target_components'
    label: 'UniProt Accessions'
  '_metadata.related_compounds.count':
    label: 'Compounds'
  '_metadata.related_activities.count':
    label: 'Activities'
  'tax_id':
    label: 'Tax ID'
chembl_document:
  'journal_full_title':
    label: 'Journal'
  'src_id':
    label: 'Source ID'
  '_metadata.source':
    label: 'Source Description'
  'pubmed_id':
    label: 'PubMed ID'
  'doi':
    label: 'DOI'
  'patent_id':
    label: 'Patent ID'
  'volume':
    label: 'Volume'
  'issue':
    label: 'Issue'
  'first_page':
    label: 'First Page'
  'doc_type':
    label: 'Document Type'
  '_metadata.related_compounds.count':
    label: 'Compounds'
  '_metadata.related_targets.count':
    label: 'Targets'
  '_metadata.related_activities.count':
    label: 'Activities'
chembl_cell_line:
  'clo_id':
    label: 'CLO ID'
  'cl_lincs_id':
    label: 'LINKS ID'
  '_metadata.related_compounds.count':
    label: 'Compounds'
  '_metadata.related_activities.count':
    label: 'Activities'
chembl_drug_indication_by_parent:
  'drug_indication.max_phase_for_ind':
    label: 'Max Phase for Indication'
  'parent_molecule.first_approval':
    label: 'First Approval'
  'drug_indication.mesh_id':
    label: 'MESH ID'
  'drug_indication.mesh_heading':
    label: 'MESH Heading'
  'efo_ids':
    based_on: 'drug_indication.efo'
    label: 'EFO IDs'
  'efo_terms':
    based_on: 'drug_indication.efo'
    label: 'EFO Terms'
  'drug_indication.indication_refs':
    label: 'References'
  'parent_molecule._metadata.drug.drug_data.synonyms':
    label: 'Synonyms'
